//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPP_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzedElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalyzedElement()
        {
            this.UsersAnalyzedElements = new HashSet<UsersAnalyzedElement>();
        }
    
        public int Id { get; set; }
        public decimal min { get; set; }
        public decimal max { get; set; }
        public string name { get; set; }
        public string nameReadable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAnalyzedElement> UsersAnalyzedElements { get; set; }

        public void Method()
        {

        }
    }
}
