//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPP_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentingSpace
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> WardId { get; set; }
    
        public virtual Ward Ward { get; set; }
    }
}
